name: deploy
# when work
on:
    push:
        branches:
            master
jobs:
    # build
    test:
        runs-on:
            ubuntu-latest
        steps:
            # clone rep
            -   name: Clone repository
                uses: actions/checkout@v4
            # test ( их нету )
            # Перемещаем все в папку для deploy
    deploy:
        runs-on: 
            ubuntu-latest
        needs: test
        steps: 
            -   name: Check repository
                uses: actions/checkout@v4
                #
            -   name: Copy new push
                run: |
                    mkdir -p deploy-temp
                    pwd
                    cp -r css/* deploy-temp/
                    cp -r img/* deploy-temp/
                    cp -r sound/* deploy-temp/
                    cp -r js/* deploy-temp/
                    cp -r index.html deploy-temp/                   
                    ls deploy-temp
            #
            -   name: Create or switch in branch
                run: |
                        git fetch origin
                        git checkout -b gh-pages origin/gh-pages
                        git rm -rf !(deploy-temp)
                        git clean -fxd
            #
            -   name: Move new files into root
                run: |
                    ls deploy-temp
                    rm -rf !(deploy-temp)
                    mv deploy-temp/* .  
                    rm -rf deploy-temp 
            -   name: Commit and push changes
                run: |
                    git add .
                    git commit -m "Deploy to GitHub Pages" || echo "No changes"
                    git push origin gh-pages -f