name: deploy
# when work
on:
    push:
        branches:
            master
jobs:
    # build
    test:
        runs-on:
            ubuntu-latest
        steps:
            # clone rep
            -   name: Clone repository
                uses: actions/checkout@v2
    deploy:
        runs-on: 
            ubuntu-latest
        needs: test
        steps: 
            -   name: Check repository
                uses: actions/checkout@v4
                #
            -   name: Copy new push
                run: |
                    mkdir -p deploy-temp/css
                    mkdir -p deploy-temp/img
                    mkdir -p deploy-temp/sound
                    mkdir -p deploy-temp/js
                    pwd
                    cp -r css/* deploy-temp/css/ > /dev/null
                    cp -r img/* deploy-temp/img > /dev/null
                    cp -r sound/* deploy-temp/sound > /dev/null
                    cp -r js/* deploy-temp/js > /dev/null
                    cp -r index.html deploy-temp/ > /dev/null                   
                    ls deploy-temp
            # деплоим
            -   name: Deploy to GitHub Pages
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    branch: gh-pages  
                    folder: deploy-temp  
                    token: ${{ secrets.GITHUB_TOKEN }}  