name: deploy
# when work
on:
    push:
        branches:
            master
jobs:
    # build
    build:
        runs-on:
            ubuntu-latest
        steps:
            # clone rep
            -   name: Clone repository
                uses: actions/checkout@v4
            # test ( их нету )
            # Перемещаем все в папку для deploy
    deploy:
        runs-on: 
            ubuntu-latest
        needs: build
        steps: 
            -   name: Check repository
                uses: actions/checkout@v4
                #
            -   name: Copy new push
                run: |
                    ls
                    cp -r ./* .
            #
            -   name: Create or switch in branch
                run: |
                    if git ls-remote --exit-code --heads origin gh-pages; then
                        git checkout gh-pages
                    else
                        git checkout -b gh-pages
                    fi
                    git rm -rf .
                    git clean -fxd
            #
            -   name: Commit and push changes
                run: |
                    git add .
                    git commit -m "Deploy to GitHub Pages" || echo "No changes"
                    git push origin gh-pages -f